const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const viewer=$('#cad-viewer');let catalog=[],current=null;
const allowed=value=>typeof value==='string'&&/^assets\/(models|renders)\/[a-z0-9._-]+$/i.test(value);
function links(entry){const options=[['src','↓ Browser GLB'],['step','↓ STEP CAD'],['native',entry.native?.endsWith('.kicad_pcb')?'↓ KiCad PCB':'↓ Original '+(entry.native?.split('.').pop().toUpperCase()||'CAD')]];return options.filter(([key])=>allowed(entry[key])).map(([key,name])=>`<a href="${esc(entry[key])}" download>${name}</a>`).join('');}
function renderList(){const query=$('#model-search').value.toLowerCase().trim(),category=$('#model-category').value,filtered=catalog.filter(e=>(category==='all'||e.category===category)&&(e.name+' '+e.category+' '+e.description).toLowerCase().includes(query));$('#model-list').innerHTML=filtered.length?filtered.map(e=>`<button data-model="${esc(e.id)}" aria-pressed="${current?.id===e.id}">${esc(e.name)}<span>${esc(e.category)}</span></button>`).join(''):'<p class="lab-help">No matching models. Try another search.</p>';$('#model-library-count').textContent=`${filtered.length} / ${catalog.length} MODELS · ORIGINAL GEOMETRY`;}
function select(id){const entry=catalog.find(e=>e.id===id);if(!entry)return;current=entry;viewer.removeAttribute('auto-rotate');$('#model-auto-rotate').setAttribute('aria-pressed','false');$('#model-load-state').textContent='LOADING GEOMETRY…';$('.model-loading').hidden=false;$('#model-snapshot').disabled=true;$('#model-title').textContent=entry.name;$('#model-category-label').textContent=entry.category.toUpperCase();$('#model-description').textContent=entry.description;viewer.alt='Interactive 3D model of '+entry.name;if(allowed(entry.poster))viewer.poster=entry.poster;else viewer.removeAttribute('poster');viewer.src=entry.src;viewer.cameraOrbit='35deg 65deg auto';viewer.cameraTarget='auto auto auto';viewer.fieldOfView='auto';$('#model-downloads').innerHTML=links(entry);$('#model-renders').innerHTML=(entry.renders||[]).filter(allowed).map((url,i)=>`<a class="render-download" href="${esc(url)}" download><img src="${esc(url.replace('.png','.webp'))}" alt="${esc(entry.name)} ${['isometric','top','bottom'][i]||'render'} view" loading="lazy"><span>↓ ${['ISOMETRIC','TOP','BOTTOM'][i]||'RENDER'} PNG</span></a>`).join('');document.querySelectorAll('[data-camera]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.camera==='35deg 65deg auto')));renderList();const url=new URL(location.href);url.searchParams.set('model',id);history.replaceState(null,'',url);}
$('#model-list').addEventListener('click',e=>{const b=e.target.closest('[data-model]');if(b)select(b.dataset.model);});$('#model-search').addEventListener('input',renderList);$('#model-category').addEventListener('change',renderList);
viewer.addEventListener('load',()=>{$('#model-load-state').textContent='READY / DRAG TO EXPLORE';$('.model-loading').hidden=true;$('#model-snapshot').disabled=false;});viewer.addEventListener('error',()=>{$('#model-load-state').textContent='VIEW UNAVAILABLE / DOWNLOAD THE CAD';$('.model-loading').hidden=true;$('#model-description').textContent=current.description+' The 3D viewer could not load this model on this device. The original CAD and render downloads remain available.';});
$('#model-auto-rotate').addEventListener('click',()=>{const active=!viewer.hasAttribute('auto-rotate');viewer.toggleAttribute('auto-rotate',active);$('#model-auto-rotate').setAttribute('aria-pressed',String(active));});
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>{viewer.cameraOrbit=b.dataset.camera;document.querySelectorAll('[data-camera]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
$('#model-reset').addEventListener('click',()=>{viewer.cameraOrbit='35deg 65deg auto';viewer.cameraTarget='auto auto auto';viewer.fieldOfView='auto';viewer.jumpCameraToGoal();document.querySelectorAll('[data-camera]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.camera==='35deg 65deg auto')));});
$('#model-background').addEventListener('click',()=>{const light=$('.model-stage').classList.toggle('light-studio');$('#model-background').setAttribute('aria-pressed',String(light));$('#model-background').textContent=light?'Dark studio':'Light studio';});
$('#model-snapshot').addEventListener('click',()=>{try{const data=viewer.toDataURL('image/png');if(!data.startsWith('data:image/png'))throw new Error('PNG capture failed');const a=document.createElement('a');a.href=data;a.download=current.id+'-view.png';document.body.append(a);a.click();a.remove();$('#model-load-state').textContent='VIEW EXPORTED / PNG';}catch{$('#model-load-state').textContent='EXPORT UNAVAILABLE / USE RENDER DOWNLOADS';}});
try{const response=await fetch('assets/models/catalog.json');if(!response.ok)throw new Error('catalog');catalog=(await response.json()).filter(e=>allowed(e.src));const groups=[...new Set(catalog.map(e=>e.category))];$('#model-category').innerHTML='<option value="all">All models</option>'+groups.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');select(new URL(location.href).searchParams.get('model')||catalog[0]?.id);}catch{$('#model-list').innerHTML='<p>The model library could not load. Refresh to try again; the source packs below remain available.</p>';}
try{const response=await fetch('assets/models/downloads.json');if(response.ok){const downloads=await response.json();$('#archive-grid').insertAdjacentHTML('beforeend',downloads.filter(d=>allowed(d.url)).map(d=>`<a href="${esc(d.url)}" download><span>LINE FOLLOWER / GROUP 13</span><strong>${esc(d.name)}</strong><span>↓ ${d.files} FILES / ${(d.bytes/1e6).toFixed(1)} MB${d.pending?' · PARTIAL SOURCE PACK':''}</span></a>`).join(''));}}catch{}
